## default
info:
  app:
    encoding: \${file.encoding}
    java.source: \${java.version}
    java.target: \${java.version}
logging:
  level:
    io.sulee.boot.springboot: DEBUG
#server:
#  port: 9000
# ExampleProperties
#example:
#  remote-address: 192.168.1.1
#  security:
#    username: admin
#    roles:
#      - USER
#      - ADMIN
#spring:
#  thymeleaf:
#    cache: false
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    beans:
#      cache:
#        time-to-live: 10s
#    shutdown:
#      enabled: true
#    health:
#      show-details: never
#    httptrace:
#      enabled: true
#---
#spring:
#  profiles: local
#logging:
#  level:
#    io.sulee.boot.spring.boot: TRACE
#---
#spring:
#  profiles: test
#server:
#  port: ${random.int[8000,9000]}
#---
#spring:
#  profiles: dev
#security:
#  user:
#    password:
#---
#spring:
#  profiles: prod
#logging:
#  level:
#    io.sulee.boot.spring.boot: INFO
#server:
#  port: 5000    # AWS Elastic Beanstalk 에서는 포트번호로 5000번을 사용해야한다.